version: '3.8'

services:
  tradingbot:
    image: ghcr.io/haiqalharona/go-tradingbot:latest
    container_name: go-tradingbot
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
